### ISSUE TITLE
Grimblast --freeze not working correctly

### ISSUE THREAD

**Issue by Kettukaa** [hyprwm/contrib#155]
### Program

Grimblast

### Maintainers of the program

@fufexan @Misterio77

### Bug or Regression?

Bug

### Description

I don't know if this is specifically a grimblast error, a hyprpicker error, or a combination of the two.  

When running `grimblast --freeze copy area`, my three monitors _do_ freeze, but I am unable to select an area to copy. Instead, when I click the screen the hyprpicker process ends and returns a color to the terminal and sometimes also sends the error `[ERR] renderSurface: PBUFFER null`, then my monitors unfreeze and I am able to select an area for a screenshot, defeating the purpose of having the freezing in the first place. 

However, sometimes when I run the grimblast command, the same error randomly has a chance of occurring, but the frozen area selection works as expected with no issue. I have no clue what conditions allow it to work correctly, but it will only do that maybe 30% of the time. Since it worked correctly, hyprpicker also does not end up outputting a color to the console. 

Running `hyprpicker -rz` also has a random chance of displaying that error message, but always freezes correctly and returns the correct color.  

Grimblast check seems to report all OK
```
❯ grimblast check             
Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH...
   grim: OK
   slurp: OK
   hyprctl: OK
   hyprpicker: OK
   wl-copy: OK
   jq: OK
   notify-send: OK
```

```
hyprpicker 0.4.5-2
grimblast-git r129.910dad4-1
```

**Comment by fufexan** [comment]
I think this is solved in git (https://github.com/hyprwm/hyprpicker/issues/122). Can you try the git hyprpicker package?

**Comment by Kettukaa** [comment]
I built hyprpicker from source and made it take precedence over my installed hyprpicker. After testing, the error message is gone but the randomly working area-selection is still present. The error message was just a red herring. Is there any diagnostic info I could provide that could help? 

I started having this area-selection issue after updating my devel (grimblast-git) packages for the first time in an untold number of months. I didn't label this bug a regression because any information about what months-old grimblast I was previously using was long gone.

**Comment by fufexan** [comment]
Great, then I'll add that back in the code. It was removed in a previous PR for some reason and I've overlooked that.
